# Generated by Django 2.1.3 on 2018-11-18 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa_xyz', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Funcionario',
            new_name='Cliente',
        ),
    ]
