# Generated by Django 2.1.3 on 2018-11-18 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa_xyz', '0002_auto_20181118_0341'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Empresa',
        ),
    ]
