# Generated by Django 2.1.3 on 2018-11-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa_xyz', '0003_auto_20181118_0443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_servico', models.CharField(max_length=100)),
                ('comissao', models.DecimalField(decimal_places=0, max_digits=2)),
            ],
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='cpf',
            new_name='cnpj',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='remuneracao',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='sobrenome',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='tempo_de_servico',
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
