# Generated by Django 2.1.3 on 2018-11-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa_xyz', '0004_auto_20181118_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_venda', models.IntegerField()),
                ('id_vendedor', models.CharField(default='0', max_length=100)),
                ('id_servico', models.CharField(max_length=100)),
                ('id_empresa', models.CharField(max_length=100)),
                ('valor_comissao', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_vendedor', models.CharField(max_length=100)),
                ('comissao_vendedor', models.DecimalField(decimal_places=0, max_digits=2)),
                ('empresa_vendedor', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
