# Generated by Django 2.1.3 on 2018-11-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa_xyz', '0006_auto_20181118_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='id_venda',
        ),
        migrations.AlterField(
            model_name='servico',
            name='comissao_servico',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='venda',
            name='valor_comissao',
            field=models.DecimalField(decimal_places=2, max_digits=8, max_length=10.0),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='comissao_vendedor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
