# Generated by Django 2.1.3 on 2018-11-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa_xyz', '0007_auto_20181118_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='comissao_servico',
            field=models.IntegerField(default=0),
        ),
    ]
