# Generated by Django 2.1.3 on 2018-11-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa_xyz', '0010_remove_venda_valor_comissao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='id_vendedor',
            field=models.CharField(default='nenhum', max_length=100),
        ),
    ]
