# Generated by Django 2.1.3 on 2018-11-19 02:35

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('empresa_xyz', '0011_auto_20181118_2019'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='servico',
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='vendedor',
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
    ]
